### ISSUE TITLE
下載的音視頻塊數量 要怎麼手動合併?

### ISSUE THREAD

**Issue by f00215k6** [Last-Order/kkr#12]
今天下載完直播後顯示了 下載的音視頻塊數量不一致請手動合併 
我用ffmpeg合併會一直出現last message repeated的提示沒辦法正常合併
如果用copy /b * V.mp4合併的話也沒辦法正常打開檔案來使用
我現在要怎麼處理?

**Comment by Last-Order** [comment]
ffmpeg concat 模式也不行吗

**Comment by f00215k6** [comment]
我用 ffmpeg.exe -f concat -safe 0 -i list.txt -c copy v.mp4的話他就視一直顯示last message repeated
然後輸出的檔案裡面有大量的停幀畫面，正常應該是33分鐘左右的檔案被他變成22小時

**Comment by Last-Order** [comment]
文件打个包传个网盘给我看下？

**Comment by f00215k6** [comment]
https://drive.google.com/file/d/1oFSiasJIyNwuAOGCKC7tpYvVwPk7_eaI/view?usp=sharing
在這邊 數量不一致的檔案我另外放在一個資料夾內

**Comment by Last-Order** [comment]
你好，我试了一下，使用二进制连接方式合并是可以正常播放的
`copy /b * output.mp4`
输出文件可能稍有问题，可以使用ffmpeg或mkvtoolnix重新混流一次就好了

**Comment by f00215k6** [comment]
可以了 我昨天用ffmpeg他會一直顯示last message repeated
然後premiere跟Freemake會直接停止回應
剛用mkvtoolnix重新處理過就正常撥放了
