### ISSUE TITLE
为何安装krr会不成功出现这个？

### ISSUE THREAD

**Issue by LaoLaoNo1** [Last-Order/kkr#19]
输入安装命令后npm i -g kkr，总提示以下：

changed 60 packages, and audited 61 packages in 1m

4 packages are looking for funding
  run `npm fund` for details

3 moderate severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

**Comment by Last-Order** [comment]
这不是安装失败 这是npm给的一些提示 无视即可
