### ISSUE TITLE
使没有开实时回放的直播也能下载回放

### ISSUE THREAD

**Issue by YellowishBread2** [Last-Order/kkr#20]
有一个叫做YTBetter的插件可以在直播没有开实时回放的情况下看到实时回放
不知道能否实现类似的功能来下载回放或者是组合一下呢
https://pastebin.com/5EiDA3VL

**Comment by Last-Order** [comment]
脚本思路很骚，很有参考价值。但是kkr走的是另一路径，所以可能无法在kkr中实现。如果将来利用了这个思路或许会换个项目名开个新坑了。
