### ISSUE TITLE
在下载刚结束的直播视频时出现了问题

### ISSUE THREAD

**Issue by G11sleeping** [Last-Order/kkr#3]
下载直播时可以使用，而且合并文件也很顺利
下载刚结束的直播视频时，下载很顺利，但是合成出现问题。

![cmd_4rtFMxkUG3](https://user-images.githubusercontent.com/75628773/101371348-9c8bb580-38e5-11eb-865b-07612457cdce.png)
![cmd_qcq0W92kFM](https://user-images.githubusercontent.com/75628773/101371359-9f86a600-38e5-11eb-847f-a175f7947520.png)
请问该如何解决这个问题呢
ffmpeg版本是2020-12-06-git-2aab42bc40-full_build-www.gyan.dev

**Comment by Last-Order** [comment]
可否提供一下发生这种情况时候的临时文件供排查

**Comment by G11sleeping** [comment]
嗯，准确来说我在除了正在直播时使用Kkr结束后是正确合并的
任何刚直播后形成的视频使用kkr都会合并失败
源文件过大，用奶牛快传
https://cowtransfer.com/s/21aa8f6c1ad74c

**Comment by Last-Order** [comment]
谢谢，我看下

**Comment by G11sleeping** [comment]
顺便能否增加手动合并的方式，避免下载了临时文件无法处理

**Comment by Last-Order** [comment]
可以 计划中

**Comment by Last-Order** [comment]
看了下，理论上应该是少了个包含视频信息的initialization segment导致ffmpeg报错，但是我看了圈没找到去哪下这玩意- -

连单个块都没法正常播放

所以，暂时没什么头绪…

另外我看不是所有视频都有这个问题，还得再研究研究

**Comment by G11sleeping** [comment]
好的麻烦啦

**Comment by fireattack** [comment]
下超过2小时的直播vod经常遇到这种情况。
`youtube-dl`有[获取segment不完全](https://github.com/ytdl-org/youtube-dl/issues/26330)导致只有最后2小时的问题，但是至少这2小时的内容可以正常播放

不知道研究下他们那边是怎么处理的有没有帮助

**Comment by Last-Order** [comment]
试着修了一下，1.2.4尝试一下

**Comment by Last-Order** [comment]
先关闭了，如果您还遇到这个问题欢迎重新开一个`issue`。
