### ISSUE TITLE
请问可以指定從哪个sq开始和结束下载回放吗?

### ISSUE THREAD

**Issue by Andy8r0X** [Last-Order/kkr#4]
有些YouTube直播一整年都不会关闭停止直播串流，
有尝试过可手动改变sq=回放数天前的内容，
就算没有开放实时回放功能，仍可下载过去内容，
计算一小时增加的sq数可以计算回推到过去的时间点。

请问kkr可以指定从哪一个sq才开始下载，到哪一个sq结束吗？谢谢开发者
`
https://r5---sn-ipoxu-un5e7.googlevideo.com/videoplayback?expire=1608303240&ei=X&ip=X.X.X.X&id=[YID].6&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160&source=yt_live_broadcast&requiressl=yes&hcs=yes&mh=R3&mm=44%2C29&mn=sn-ipoxu-un5e7%2Csn-ipoxu-un5e7&ms=lva%2Crdu&mv=m&mvi=5&pl=20&rmhost=r1---sn-ipoxu-un5e7.googlevideo.com&shardbypass=yes&smhost=r1---sn-ipoxu-un5d.googlevideo.com&initcwndbps=632500&vprv=1&live=1&hang=1&noclen=1&mime=video%2Fmp4&ns=X&gir=yes&mt=1608281305&fvip=1&keepalive=yes&c=WEB&n=X&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Clive%2Chang%2Cnoclen%2Cmime%2Cns%2Cgir&sig=X&lsparams=hcs%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crmhost%2Cshardbypass%2Csmhost%2Cinitcwndbps&lsig=X&alr=yes&cpn=X&cver=2.20201216.08.00&sq=2000000&rn=23&rbuf=5265
`

**Comment by Last-Order** [comment]
kkr用的不是videoplayback这套，一时半会加不上。DASH那边每一块有各自的lmt没法遍历，所以做不了。

综上，暂时无法支持。
