### ISSUE TITLE
直播結束後手動合併檔案

### ISSUE THREAD

**Issue by katy50306** [Last-Order/kkr#7]
今天以下列命令執行kkr
kkr -d "https://www.youtube.com/watch?v=weKQ13m2GDI" --live
下到17482時 直播結束
以mpc打開17482看起來是最後塊
但cmd界面沒有執行合併動作
看起來是不知道直播結束的樣子

想請問若要手動合併的話
該如何操作呢？
或是可用kkr下什麼樣的命令使其合併呢？

謝謝

**Comment by Last-Order** [comment]
没有自动合并的原因是什么呢，能否贴下log
手动合并比较麻烦，可以先试二进制链接，不行的话用ffmpeg concat

**Comment by katy50306** [comment]
我整理一下，看這樣會不會比較清楚

[問題]
直播結束後，kkr仍維持下載狀態，未進行合併。(kkr認為未達直播結束條件？)
![kkr-s1](https://user-images.githubusercontent.com/6602297/107176439-5dbfcc00-6a0a-11eb-9221-e213251d45c2.PNG)

[環境]
win10 20H2(19042.746)
node 14.15.4
ffmpeg version 2021-01-20-git-2021dbe1d6-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
kkr路徑：C:\Users\XXX\AppData\Roaming\npm\node_modules\kkr
下載路徑：C:\Users\XXX\KKR\

[說明]
1. 直播總長度約5小時
2. 直播中直播主因為電腦問題重啟電腦，中斷約3分鐘
3. 直播結束刪檔前以 kkr -d "https://www.youtube.com/watch?v=weKQ13m2GDI" 進行下載，僅得出最後2hr之影片
4. 將kkr下載取得之影片片段，取少數片段以mpc播出，似乎正常，最後片段17482也是結束畫面無誤。
5. 以ffmepg進行合併，指令
ffmpeg.exe -f concat -safe 0 -i list.txt -c copy video.mp4
ffmpeg.exe -i video.mp4 -i audio.mp4 -c copy output.mp4
命令執行ok，播放部份待確認(人在公司不方便)

[log]
不確定是否有.log檔，我找不到放在哪裡

[額外說明]
1. 同issue #3 ，希望增加手动合并的方式，避免下载了临时文件无法处理

這部份我的想法
kkr 先抓檔->確認直播結束->合併片段->完成合併
目前只能從抓檔開始
但此例直播已刪除就等於無法進行後續合併程序

片段其實都抓下來了
希望能有參數或選項，能跳過抓檔，直接從合併片段開始

2. > 手动合并比较麻烦，可以先试二进制链接，不行的话用ffmpeg concat

二进制链接部份，是否可舉一些簡單命令或教學文章供參考？

謝謝

**Comment by Last-Order** [comment]
> 直播結束後，kkr仍維持下載狀態，未進行合併

这种情况手动按下ctrl+c可以进入合并流程

> 希望能有參數或選項，能跳過抓檔，直接從合併片段開始

比较困难，因为缺块信息等已经丢失了，不知道从哪分段。计划中。

> 二进制链接部份，是否可舉一些簡單命令或教學文章供參考？

Windows的话，进入临时文件夹将文件调整好顺序（可能需要第三方软件帮助，给分片文件名前添加0，例如1 -> 00001，否则顺序会错乱），然后使用`copy /b * output.mp4`即可二进制连接合并。

**Comment by katy50306** [comment]
暫時解決
ctrl+c 會先跳出"获取MPD列表失败"
多按幾次就開始合併了

用ffmpeg concat影像時間軸會有問題
mkvmerge沒辦法一次併這麼多檔
還是您的工具簡單好用
