### ISSUE TITLE
在抓取直播的时候总是会出现“获取MPD列表失败”

### ISSUE THREAD

**Issue by nowata** [Last-Order/kkr#8]
尝试过了很多其它的办法，还是不行。
只要是抓取未开启油管直播回放的直播都会是不是跳出获取MPD列表失败。
然后就会断档，到目前为止都不知道该如何解决。

**Comment by Last-Order** [comment]
加一下`--verbose`看下具体错误

**Comment by nowata** [comment]
看了一下，断档的原因不是“获取MPD列表失败”。
是因为虽然显示“正获取MPD列表”“获取获取MPD列表失成功”但还是会时不时少抓一段音频或者视频。
这种情况会不会是梯子的问题呢？

**Comment by Last-Order** [comment]
加一下`--verbose`贴一下Log呀……你这让我盲猜啥呢

**Comment by nowata** [comment]
D:\capture>kkr -d https://www.youtube.com/watch?v=MP99yErC_PM --live --verbose
使用至多 10 线程下载
正在获取视频信息
视频标题: 【UNDERTALE】初見Gルートへ。その３。【天音かなた/ホロライブ】
是否启用DVR: false; 低延迟视频: true; 视频延迟模式: MDE_STREAM_OPTIMIZATIONS_RENDERER_LATENCY_ULTRA_LOW; 是否为首播: false
正获取MPD列表
获取MPD列表成功
audio#9454 已下载
audio#9455 已下载
audio#9456 已下载
video#9454 已下载
video#9456 已下载
video#9455 已下载
正获取MPD列表
获取MPD列表成功
audio#9457 已下载
audio#9458 已下载
video#9457 已下载
video#9458 已下载
正获取MPD列表
获取MPD列表成功
audio#9459 已下载
audio#9460 已下载
video#9460 已下载
video#9459 已下载
正获取MPD列表
获取MPD列表成功
audio#9461 已下载
audio#9462 已下载
video#9462 已下载
video#9461 已下载
正获取MPD列表
获取MPD列表成功
audio#9463 已下载
audio#9464 已下载
video#9464 已下载
video#9463 已下载
正获取MPD列表
获取MPD列表成功
audio#9466 已下载
audio#9465 已下载
video#9466 已下载
video#9465 已下载
正获取MPD列表
获取MPD列表成功
audio#9467 已下载
audio#9468 已下载
video#9467 已下载
video#9468 已下载
正获取MPD列表
获取MPD列表成功
audio#9470 已下载
audio#9469 已下载
video#9470 已下载
video#9469 已下载
正获取MPD列表
获取MPD列表成功
audio#9471 已下载
audio#9472 已下载
video#9471 已下载
video#9472 已下载
正获取MPD列表
获取MPD列表成功
audio#9473 已下载
audio#9474 已下载
video#9474 已下载
video#9473 已下载
正获取MPD列表
获取MPD列表成功
audio#9475 已下载
audio#9476 已下载
video#9475 已下载
video#9476 已下载
正获取MPD列表
获取MPD列表成功
audio#9478 已下载
audio#9477 已下载
video#9478 已下载
video#9477 已下载
正获取MPD列表
获取MPD列表成功
audio#9480 已下载
audio#9479 已下载
video#9480 已下载
video#9479 已下载
正获取MPD列表
获取MPD列表成功
audio#9482 已下载
audio#9481 已下载
video#9482 已下载
video#9481 已下载
正获取MPD列表
获取MPD列表成功
audio#9484 已下载
audio#9483 已下载
video#9484 已下载
video#9483 已下载
正获取MPD列表
获取MPD列表成功
audio#9485 已下载
audio#9486 已下载
video#9485 已下载
video#9486 已下载
正获取MPD列表
获取MPD列表成功
audio#9488 已下载
audio#9487 已下载
video#9487 已下载
video#9488 已下载
正获取MPD列表
获取MPD列表成功
audio#9489 已下载
audio#9490 已下载
video#9489 已下载
video#9490 已下载
正获取MPD列表
获取MPD列表成功
audio#9491 已下载
audio#9492 已下载
video#9491 已下载
video#9492 已下载
正获取MPD列表
获取MPD列表成功
audio#9494 已下载
audio#9493 已下载
video#9493 已下载
video#9494 已下载
正获取MPD列表
获取MPD列表成功
audio#9495 已下载
audio#9496 已下载
video#9496 已下载
video#9495 已下载
正获取MPD列表
获取MPD列表成功
audio#9497 已下载
audio#9498 已下载
video#9498 已下载
video#9497 已下载
正获取MPD列表
获取MPD列表成功
audio#9500 已下载
audio#9499 已下载
video#9499 已下载
video#9500 已下载
正获取MPD列表
获取MPD列表成功
audio#9502 已下载
audio#9501 已下载
video#9502 已下载
video#9501 已下载
正获取MPD列表
获取MPD列表成功
audio#9503 已下载
audio#9504 已下载
video#9503 已下载
video#9504 已下载
正获取MPD列表
获取MPD列表成功
audio#9506 已下载
audio#9505 已下载
video#9506 已下载
video#9505 已下载
正获取MPD列表
获取MPD列表成功
audio#9508 已下载
audio#9507 已下载
video#9508 已下载
video#9507 已下载
正获取MPD列表
获取MPD列表成功
audio#9510 已下载
audio#9509 已下载
video#9510 已下载
video#9509 已下载
正获取MPD列表
获取MPD列表成功
audio#9511 已下载
audio#9512 已下载
video#9512 已下载
video#9511 已下载
正获取MPD列表
获取MPD列表成功
audio#9513 已下载
audio#9514 已下载
video#9514 已下载
video#9513 已下载
正获取MPD列表
获取MPD列表成功
audio#9515 已下载
audio#9516 已下载
video#9515 已下载
video#9516 已下载
正获取MPD列表
获取MPD列表成功
audio#9517 已下载
audio#9518 已下载
video#9518 已下载
video#9517 已下载
正获取MPD列表
获取MPD列表成功
audio#9520 已下载
audio#9519 已下载
video#9520 已下载
video#9519 已下载
正获取MPD列表
获取MPD列表成功
audio#9522 已下载
audio#9521 已下载
video#9521 已下载
video#9522 已下载
正获取MPD列表
获取MPD列表成功
audio#9524 已下载
audio#9523 已下载
video#9524 已下载
video#9523 已下载
正获取MPD列表
获取MPD列表成功
audio#9526 已下载
audio#9525 已下载
video#9525 已下载
video#9526 已下载
正获取MPD列表
获取MPD列表成功
audio#9528 已下载
audio#9527 已下载
video#9527 已下载
video#9528 已下载
正获取MPD列表
获取MPD列表成功
audio#9529 已下载
audio#9530 已下载
video#9530 已下载
video#9529 已下载
正获取MPD列表
获取MPD列表成功
audio#9532 已下载
audio#9531 已下载
video#9532 已下载
video#9531 已下载
正获取MPD列表
获取MPD列表成功
audio#9533 已下载
audio#9534 已下载
video#9534 已下载
video#9533 已下载
正获取MPD列表
获取MPD列表成功
audio#9535 已下载
audio#9536 已下载
video#9535 已下载
video#9536 已下载
正获取MPD列表
获取MPD列表成功
audio#9538 已下载
audio#9537 已下载
video#9538 已下载
video#9537 已下载
正获取MPD列表
获取MPD列表成功
audio#9540 已下载
audio#9539 已下载
video#9540 已下载
video#9539 已下载
正获取MPD列表
获取MPD列表成功
audio#9542 已下载
audio#9541 已下载
video#9542 已下载
video#9541 已下载
正获取MPD列表
正获取MPD列表
正获取MPD列表
Error: 获取MPD列表失败
获取MPD列表失败
获取MPD列表成功
获取MPD列表成功
正获取MPD列表
audio#9547 已下载
audio#9548 已下载
video#9548 已下载
video#9549 已下载
video#9547 已下载
获取MPD列表成功
audio#9549 已下载
audio#9550 已下载
video#9550 已下载
正获取MPD列表
获取MPD列表成功
audio#9551 已下载
audio#9552 已下载
video#9552 已下载
video#9551 已下载
正获取MPD列表
获取MPD列表成功
audio#9554 已下载
audio#9553 已下载
video#9553 已下载
video#9554 已下载
正获取MPD列表
获取MPD列表成功
audio#9555 已下载
audio#9556 已下载
video#9556 已下载
video#9555 已下载
正获取MPD列表
获取MPD列表成功
audio#9557 已下载
audio#9558 已下载
video#9558 已下载
video#9557 已下载
正获取MPD列表
获取MPD列表成功
audio#9559 已下载
audio#9560 已下载
video#9559 已下载
video#9560 已下载
正获取MPD列表
获取MPD列表成功
audio#9561 已下载
audio#9562 已下载
video#9561 已下载
video#9562 已下载
正获取MPD列表
获取MPD列表成功
audio#9563 已下载
audio#9564 已下载
video#9563 已下载
video#9564 已下载
正获取MPD列表
获取MPD列表成功
audio#9565 已下载
audio#9566 已下载
video#9566 已下载
video#9565 已下载
正获取MPD列表
获取MPD列表成功
audio#9567 已下载
audio#9568 已下载
video#9567 已下载
video#9568 已下载
正获取MPD列表
获取MPD列表成功
audio#9569 已下载
audio#9570 已下载
video#9570 已下载
video#9569 已下载
正获取MPD列表
获取MPD列表成功
audio#9572 已下载
audio#9571 已下载
video#9572 已下载
video#9571 已下载
正获取MPD列表
获取MPD列表成功
audio#9574 已下载
audio#9573 已下载
video#9574 已下载
video#9573 已下载
正获取MPD列表
获取MPD列表成功
audio#9576 已下载
audio#9575 已下载
video#9576 已下载
video#9575 已下载
正获取MPD列表
获取MPD列表成功
audio#9578 已下载
audio#9577 已下载
video#9578 已下载
正获取MPD列表
video#9577 已下载
获取MPD列表成功
audio#9580 已下载
audio#9579 已下载
video#9579 已下载
video#9580 已下载
正获取MPD列表
获取MPD列表成功
audio#9581 已下载
audio#9582 已下载
video#9581 已下载
video#9582 已下载
正获取MPD列表
获取MPD列表成功
audio#9584 已下载
audio#9583 已下载
video#9583 已下载
video#9584 已下载
正获取MPD列表
获取MPD列表成功
audio#9586 已下载
audio#9585 已下载
video#9585 已下载
video#9586 已下载
正获取MPD列表
获取MPD列表成功
audio#9588 已下载
audio#9587 已下载
video#9587 已下载
video#9588 已下载
正获取MPD列表
获取MPD列表成功
audio#9590 已下载
audio#9589 已下载
video#9589 已下载
video#9590 已下载
正获取MPD列表
获取MPD列表成功
audio#9591 已下载
audio#9592 已下载
video#9592 已下载
video#9591 已下载
正获取MPD列表
获取MPD列表成功
audio#9593 已下载
audio#9594 已下载
video#9594 已下载
video#9593 已下载
正获取MPD列表
获取MPD列表成功
audio#9595 已下载
audio#9596 已下载
video#9596 已下载
video#9595 已下载
Ctrl+C 被按下 等待当前任务下载完毕
序列不连续 将输出多个文件
输出文件1: #9454-#9542
输出文件2: #9547-#9596
为第 1 个输出文件合并视频
[合并文件] [████████████████████████████████████████] 100% | ETA: 0s | 89/89
为第 1 个输出文件合并音频
[合并文件] [████████████████████████████████████████] 100% | ETA: 0s | 89/89
混流第 1 个输出文件
frame= 5340 fps=0.0 q=-1.0 Lsize=   20494kB time=00:01:28.98 bitrate=1886.7kbits/s speed=2.26e+03x

为第 2 个输出文件合并视频
[合并文件] [████████████████████████████████████████] 100% | ETA: 0s | 50/50
为第 2 个输出文件合并音频
[合并文件] [████████████████████████████████████████] 100% | ETA: 0s | 50/50
混流第 2 个输出文件
frame= 3000 fps=0.0 q=-1.0 Lsize=   14357kB time=00:00:49.99 bitrate=2352.5kbits/s speed=2.02e+03x

清理临时文件
输出了多个文件 列表如下
#9454 - #9542 -> 【UNDERTALE】初見Gルートへ。その３。【天音かなたホロライブ】_1.mp4
#9547 - #9596 -> 【UNDERTALE】初見Gルートへ。その３。【天音かなたホロライブ】_2.mp4
终止批处理操作吗(Y/N)?

大概是这样，之前表述不当非常抱歉，添麻烦了
还有，时不时会冒出“Error: Client network socket disconnected before secure TLS connection was established”

**Comment by Last-Order** [comment]
超低延迟模式的直播对网络要求很高，你这个应该是中间有几次请求列表失败了（网络原因）导致丢块

**Comment by nowata** [comment]
好的好的，非常感谢，添麻烦了添麻烦了
