### ISSUE TITLE
建议：增加一个线程延时选项

### ISSUE THREAD

**Issue by fireattack** [Last-Order/kkr#9]
在下载已经播放了一段时间的直播时，由于会高并发下载之前的块，经常（如果使用默认线程数，准确地说是每次）会被服务器ban，而且一ban就是5到10分钟起。
这个问题主要出现在音频块上，由于文件太小，极端情况我甚至遇到过设置为线程为1还触发rate limit被ban的情况（一般倒是线程2以内就基本不会被ban）。

不知道能否增加一个最短线程间隔的选项，或者是最大连接发起频率

**Comment by Last-Order** [comment]
现在Live模式加了`--cooldown`参数，其作用于每个下载任务后，当`--threads 1`时表现为下载间隔恰为设定值。非 Live 模式依赖 shua 的功能，先延后。

**Comment by fireattack** [comment]
Thanks
